version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ..:/var/www/html
    depends_on:
      - db
    networks:
      - devnet

  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: serenato_db
      MYSQL_USER: serenato_user
      MYSQL_PASSWORD: secret
    ports:
      - '3306:3306'
    networks:
      - devnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - devnet

networks:
  devnet:
